### ISSUE TITLE
Keep square root 

### ISSUE THREAD

**Issue by bgermann** [jd-s/StrongsDicGerman#2]
You write 'v was changed to "von"' but the actual character used in the docx source is the square root. I think this should be kept.

**Comment by jd-s** [comment]
The docx was not the source for this version, but the plain text version, which has a "v". I will contact the author to hear his opinion on it.

**Comment by bgermann** [comment]
That was then a conversion error by the program that converted to .txt

**Comment by bgermann** [comment]
I guess this is one of the reasons why in the original license the author wants to be contacted for redistributions in non-PDF format.

**Comment by jd-s** [comment]
And this is what I did. He did not reject my modifications but since you are heavily insisting on keeping the square root, I will hear his view on it and I will also check how it integrates into the SWORD environment.
