### ISSUE TITLE
FYI: Module is included in SWORD's repository

### ISSUE THREAD

**Issue by bgermann** [jd-s/StrongsDicGerman#4]
Crosswire maintains it at https://gitlab.com/crosswire-bible-society/StrongsDicGerman

**Comment by jd-s** [comment]
... and what does that exactly mean? I can no longer make improvements?

**Comment by bgermann** [comment]
Sure you can. Nobody keeps you from doing that. It just means that people can fetch this module via the normal sword install.

**Comment by jd-s** [comment]
Ah, but I have to take care to merge back the improvements from that repository. This makes it impossible for me, since I have to assign my time wisely.
